"""
Vectrax eToro — Signal Recorder
=================================
Every PRE-OPERABLE or OPERABLE scenario generated by the market observer
is saved as a signal with a unique ID and a directional prediction.

The signal captures:
  - When: timestamp, session name
  - What: symbol, direction (buy/sell), price, ATR, relative volume
  - Prediction: expected_direction, entry_price, invalidation_price
  - State: OPERABLE or PRE_OPERABLE, conditions met (bitmask)
  - Outcome: resolved later by outcome_tracker.py

Persistence: JSONL at ~/.vectrax/etoro_signals.jsonl
Each line is one signal (append-only, never modified — outcome added in place).
"""
from __future__ import annotations

import hashlib
import json
import logging
import os
import time
from dataclasses import dataclass, asdict, field
from enum import Enum
from typing import Any, Dict, List, Optional

logger = logging.getLogger("vectrax.etoro.signal_recorder")

_SIGNALS_FILE = os.path.join(
    os.path.expanduser("~"), ".vectrax", "etoro_signals.jsonl"
)

# ── Enums ────────────────────────────────────────────────────────────

class SignalStatus(str, Enum):
    PENDING  = "pending"   # signal recorded, outcome not yet resolved
    WIN      = "win"       # price moved in predicted direction
    LOSS     = "loss"      # price moved against prediction / SL hit
    NEUTRAL  = "neutral"   # price did not move meaningfully
    EXPIRED  = "expired"   # outcome window passed, insufficient movement


class ScenarioType(str, Enum):
    OPERABLE     = "OPERABLE"
    PRE_OPERABLE = "PRE_OPERABLE"


# ── Signal dataclass ─────────────────────────────────────────────────

@dataclass
class MarketSignal:
    # Identity
    signal_id:          str
    timestamp:          float
    symbol:             str
    direction:          str        # "buy" | "sell"
    scenario:           str        # ScenarioType value

    # Market state at signal time
    price:              float
    atr:                float
    rel_volume:         float
    session:            str
    conditions_met:     int        # count 3 or 4
    conditions_names:   List[str]  # names of met conditions

    # Prediction
    entry_price:        Optional[float]
    invalidation_price: Optional[float]

    # Outcome (filled in by outcome_tracker)
    status:             str = SignalStatus.PENDING.value
    outcome_price:      Optional[float] = None
    outcome_timestamp:  Optional[float] = None
    return_pct:         Optional[float] = None
    sl_touched:         bool = False
    outcome_window_h:   float = 4.0   # hours to evaluate outcome

    def to_dict(self) -> Dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: Dict) -> "MarketSignal":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})


# ── File I/O ─────────────────────────────────────────────────────────

def _ensure_dir() -> None:
    os.makedirs(os.path.dirname(_SIGNALS_FILE), exist_ok=True)


def _make_signal_id(symbol: str, ts: float, direction: str) -> str:
    raw = f"{symbol}:{direction}:{ts:.0f}"
    return "SIG-" + hashlib.md5(raw.encode()).hexdigest()[:8].upper()


def load_signals(limit: int = 0, status_filter: Optional[str] = None) -> List[MarketSignal]:
    """Load signals from disk. limit=0 means all."""
    _ensure_dir()
    if not os.path.exists(_SIGNALS_FILE):
        return []
    signals = []
    try:
        with open(_SIGNALS_FILE) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    d = json.loads(line)
                    if status_filter and d.get("status") != status_filter:
                        continue
                    signals.append(MarketSignal.from_dict(d))
                except Exception:
                    pass
    except Exception as e:
        logger.warning("load_signals error: %s", e)
    if limit:
        return signals[-limit:]
    return signals


def save_signal(sig: MarketSignal) -> None:
    """Append a new signal to the JSONL file."""
    _ensure_dir()
    try:
        with open(_SIGNALS_FILE, "a") as f:
            f.write(json.dumps(sig.to_dict(), ensure_ascii=False) + "\n")
        logger.info(
            "[SIGNAL] %s | %s %s | price=%.5g | conditions=%d/4 | status=%s",
            sig.signal_id, sig.direction.upper(), sig.symbol,
            sig.price, sig.conditions_met, sig.status,
        )
    except Exception as e:
        logger.error("save_signal error: %s", e)


def update_signal(signal_id: str, updates: Dict) -> bool:
    """
    Update fields of an existing signal in the JSONL file.
    Rewrites the entire file (signals file is expected to be small <10MB).
    Returns True if the signal was found and updated.
    """
    _ensure_dir()
    if not os.path.exists(_SIGNALS_FILE):
        return False
    lines = []
    found = False
    try:
        with open(_SIGNALS_FILE) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    d = json.loads(line)
                    if d.get("signal_id") == signal_id:
                        d.update(updates)
                        found = True
                    lines.append(json.dumps(d, ensure_ascii=False))
                except Exception:
                    lines.append(line)

        with open(_SIGNALS_FILE, "w") as f:
            f.write("\n".join(lines) + "\n")
    except Exception as e:
        logger.error("update_signal error: %s", e)
        return False
    return found


# ── Main public function ─────────────────────────────────────────────

def record_from_scenario(
    symbol: str,
    direction: str,
    price: float,
    scenario_state: str,         # "OPERABLE" or "PRE-OPERABLE"
    conditions_met: int,
    conditions_names: List[str],
    atr: float = 0.0,
    rel_volume: float = 1.0,
    session: str = "",
    entry_price: Optional[float] = None,
    invalidation_price: Optional[float] = None,
    outcome_window_h: float = 4.0,
) -> MarketSignal:
    """
    Create and save a new signal from a market observer scenario result.
    Returns the saved MarketSignal.
    """
    ts = time.time()
    sid = _make_signal_id(symbol, ts, direction)

    # Normalize scenario state
    sc = ScenarioType.OPERABLE.value if "OPERABLE" in scenario_state.upper() and "PRE" not in scenario_state.upper() \
        else ScenarioType.PRE_OPERABLE.value

    sig = MarketSignal(
        signal_id=sid,
        timestamp=ts,
        symbol=symbol.upper(),
        direction=direction.lower(),
        scenario=sc,
        price=price,
        atr=atr,
        rel_volume=rel_volume,
        session=session,
        conditions_met=conditions_met,
        conditions_names=conditions_names,
        entry_price=entry_price,
        invalidation_price=invalidation_price,
        outcome_window_h=outcome_window_h,
    )
    save_signal(sig)
    return sig


def get_pending_signals() -> List[MarketSignal]:
    """Return all signals awaiting outcome resolution."""
    return load_signals(status_filter=SignalStatus.PENDING.value)


def get_signal_stats() -> Dict[str, Any]:
    """Return aggregate statistics of all recorded signals."""
    signals = load_signals()
    if not signals:
        return {"total": 0, "pending": 0, "resolved": 0,
                "wins": 0, "losses": 0, "neutral": 0, "expired": 0, "win_rate": 0.0}

    total   = len(signals)
    pending = sum(1 for s in signals if s.status == SignalStatus.PENDING.value)
    wins    = sum(1 for s in signals if s.status == SignalStatus.WIN.value)
    losses  = sum(1 for s in signals if s.status == SignalStatus.LOSS.value)
    neutral = sum(1 for s in signals if s.status == SignalStatus.NEUTRAL.value)
    expired = sum(1 for s in signals if s.status == SignalStatus.EXPIRED.value)
    resolved = wins + losses + neutral + expired
    win_rate = round(wins / max(1, wins + losses) * 100, 1)

    return {
        "total":    total,
        "pending":  pending,
        "resolved": resolved,
        "wins":     wins,
        "losses":   losses,
        "neutral":  neutral,
        "expired":  expired,
        "win_rate": win_rate,
    }
